public enum MistakeType
{
    CONCRETE_MIXER_WRONG_COMPONENTS_ORDER_MISTAKE,
    CONCRETE_MIXER_WRONG_COMPONENTS_CAPACITY_MISTAKE,
    CONCRETE_MIXER_DISABLE_FILL_MISTAKE,
    FURNACE_OPEN_DOOR_MISTAKE,
    FURNACE_DRYING_WRONG_TIME_MISTAKE,
    FURNACE_DRYING_WRONG_TEMP_MISTAKE,
    FURNACE_CALCINATION_WRONG_TIME_MISTAKE,
    FURNACE_CALCINATION_WRONG_TEMP_MISTAKE,
    FURNACE_COOLINGDOWN_WRONG_TIME_MISTAKE,
    FURNACE_COOLINGDOWN_WRONG_TEMP_MISTAKE,
    EXTRUDER_SKIP_MISTAKE
}